# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#title: Your awesome title
collections_dir: collections

collections:
  articles:
    output: true
  landings:
    output: true
  landing_lists:
    output: true
  landing_locations:
    output: true
  landing_technologies:
    output: false # we do not render technologies page without a location
  landing_location_technologies:
    output: true

defaults:
  - scope:
      type: landing_lists
    values:
      layout: landing_list
  - scope:
      type: landing_locations
    values:
      layout: landing_list
  - scope:
      type: landing_location_technologies
    values:
      layout: landing

url: "https://teambrookvale.com.au"      

plugins:
    - jekyll-sitemap
    - jekyll-last-modified-at

description: "Team Brookvale has extensive experience in social media API integration and developing automation software. We provide complete software development services from idea through development to maintenance."

keywords: "software development, software developer, sydney, brookvale, northern beaches, melbourne, brisbane, gold coast, software, development, business, iot, mobile development, ios, android, web development, business apps, game development, dotnet, react, redux"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - automation